### ISSUE TITLE
Remove README images from the main codebase and host them somewhere else 

### ISSUE THREAD

**Issue by boemska-nik** [Boemska/h54s#16]
It didn't occur to me that not everyone wants to clone them along with the code

**Comment by bojan88** [comment]
![chrome_dws](https://cloud.githubusercontent.com/assets/1783133/11691304/abd0cb1a-9e9a-11e5-8d5e-9706b62a272f.png)
![loggedin](https://cloud.githubusercontent.com/assets/1783133/11691306/aff89f10-9e9a-11e5-9edd-f9a4d4e8c1b1.gif)
![loggedout](https://cloud.githubusercontent.com/assets/1783133/11691310/b316633a-9e9a-11e5-81e6-450ac7545ea4.gif)
![loggedout](https://cloud.githubusercontent.com/assets/1783133/11691314/b763135c-9e9a-11e5-9e2a-cad9c4b50bd4.png)
