### ISSUE TITLE
Data step variables named USER getting populated with &SYSUSERID in client

### ISSUE THREAD

**Issue by rawsas** [Boemska/h54s#27]
Sent from SAS:

```
data sasparams;
  USER="Sugarhill Gang";
run;
%hfsHeader;
%hfsOutDataset(jsParams,WORK, sasparams);
%hfsFooter;
```

Received by browser:
![image](https://cloud.githubusercontent.com/assets/4420615/12039079/585e83b2-ae55-11e5-98fa-0f720c87a089.png)

So maybe USER is a reserved variable name in H54s..  If so should probably be documented somewhere?  Ideally though this variable name would be available to developers, in order to avoid unexpected behaviour.

**Comment by boemska-nik** [comment]
Need a workaround for SQL reserved word USER
