### ISSUE TITLE
SPKs containing the STPs are missing from Examples

### ISSUE THREAD

**Issue by cj13579** [Boemska/h54s#29]
The Stored Procedures that are required for the example applications to work are not included as part of the repository rendering the examples from a "seeing an functioning fully" perspective useless.

**Comment by boemska-nik** [comment]
Just had a look at the other samples as well - a lot of them are out of date, as the examples have been mostly superseded by the seed app(s). 

We'll sort it out in the next couple of days and provide an .spk to go with them.

**Comment by cj13579** [comment]
Closing this issue as redundant. This issue was created before the existence of the [Angular Seed App](https://github.com/Boemska/h54s-angular-seed-app) and the [Open UI Seed App](https://github.com/Boemska/h54s-openui5-seed-app) which effectively removed the requirements for these SPKs.
