### ISSUE TITLE
Provide metadata mechanism for identify DATETIME variables

### ISSUE THREAD

**Issue by allanbowe** [Boemska/h54s#44]
The current version of the adaptor will attempt to convert any variables prefixed with DT_ to a javascript datetime (and vice versa when coming back to SAS).

This can feasibly cause issues / require workarounds should such variables be passed without the intention to translate them.

A mechanism should exist to allow datetime variables to be identified separately from the variable name itself.

**Comment by cj13579** [comment]
Agree. With version 2.0 of the adapter this functionality has been removed because it is safer when this is explicitly handled by the developer. To send dates to SAS for processing you'd use the existing `toSasDatetime()` function. For example:

```js
var jsDate = new Date();
var sasDate = h54s.toSasDateTime(jsDate);

var table = new h54s.SasData([
{
    "some_date": sasDate
}], 'data');
```

Closing.
