### ISSUE TITLE
Standardisation of Status message and Error object

### ISSUE THREAD

**Issue by boemska-nik** [Boemska/h54s#45]
This is an extension of issue #41 

At the moment, SAS returns a `status` from the adapter, which was a placeholder that we were always going to standardise. 

So how about this:

a ` "status": "success" ` is the standard response for a successful execution of whatever it is that SAS was doing. A status of anything else (an example of which is the existing `  "status" : "inputTableNotFound" ` returned by `%hfsErrorCheck` and already outlined in the README), should be considered an error and throw an `err` object that is [already documented in the readme](https://github.com/Boemska/h54s#callsasprogram-tablesobj-callback). 

For this type of SAS-thrown backend error we should implement a  new `err.type` of `programError`, and the `err.type = 'programError'` object should then include two new properties: `err.status` and `err.message`.

I'll document the mechanisms to implement this error throwing from the SAS side separately.

**Comment by bojan88** [comment]
Added in bcd6c98272380f9a52fbb69d7dc89c1cf020a9e5

**Comment by bojan88** [comment]
Readme updated in d970c763512da369e2a0501ac17fd0d2c13c0316
