### ISSUE TITLE
triple trouble

### ISSUE THREAD

**Issue by allanbowe** [Boemska/h54s#46]
The presence of particular macro variables (`type` and `name`) can cause the adapter to fail due to incorrect use of triple ampersands (`&&&`) - eg `&&&type&colNo`.  In these cases, a double ampersand is needed to cause the desired resolution.

**Comment by boemska-nik** [comment]
Pretty sure I remember Alan Mason teaching us macro in 2009 in Marlow and explaining how triple ampersands are exactly the same as double ampersands, but that for some reason triple is better. 

Np in merging this, but can you give me some steps to replicate the problem for the sake of education?

**Comment by allanbowe** [comment]
So the issue currently is that, in the first pass, we get:

`&&` resolves to `&`
`&type` does not exist, so resolves to `&type`  <<< herein lies the issue
`&colNo` resolves to `1`

giving:
`&&type1`

Now:
`&&` resolves to `&`

Giving:
`&type1`

which resolves to the desired variable.

To replicate the problem, simply declare a macro variable called TYPE (or NAME).

**Comment by boemska-nik** [comment]
Just updating... this will become irrelevant with the next release, but will need to be addressed for the 'legacy' version

**Comment by cj13579** [comment]
This issue was resolved as of the v1.0 release. 

Closing.
