### ISSUE TITLE
Spec length for UTF8 encoded strings seems to always be 2 characters short

### ISSUE THREAD

**Issue by boemska-nik** [Boemska/h54s#53]
Pretty sure it's down to this:

https://github.com/Boemska/h54s/blob/2021a9cae456530d2f7918b6a053d00b903059a8/src/sasData.js#L198

It works fine when there are no multibyte characters involved. This should also solve the `PROC JSON` bug we've been seeing with the utf8 tests, as they've been failing when the last character has been a triple byte char split truncated by 2 bytes.

**Comment by bojan88** [comment]
Fixed in 2021a9cae456530d2f7918b6a053d00b903059a8, and changed test for UTF-8. It's working now with 3-byte characters
