### ISSUE TITLE
Semi-duplicate of issue #52

### ISSUE THREAD

**Issue by boemska-nik** [Boemska/h54s#54]
https://github.com/Boemska/h54s/blob/2021a9cae456530d2f7918b6a053d00b903059a8/src/sasData.js#L201

The replace here should also be global (and the typo needs to be corrected)

We also need to consider whether we need this, or if it is better to allow developers to explicitly stringify objects and have them stored as strings, as we do now where this is uesd. Either is doable but we need a solid mechanism for identifying these on the way back from SAS (eg. a column name prefix), same as we do with the dates.

**Comment by allanbowe** [comment]
column prefixes are bad.  We should use a different mechanism for sure..
