### ISSUE TITLE
Is this to handle the infinite loop when app is on http but SAS is on HTTPS?

### ISSUE THREAD

**Issue by boemska-nik** [Boemska/h54s#55]
https://github.com/Boemska/h54s/blob/96b90a678605768aaf4bcb9eeb010cc0a7722b61/src/methods/index.js#L220

**Comment by bojan88** [comment]
Yes. It's documented as "Unable to login" error. It can happen when you have one hostUrl, and SAS is redirecting you to another origin, and doesn't accept log in
