### ISSUE TITLE
Endless loop when authenticating

### ISSUE THREAD

**Issue by rohnny** [Boemska/h54s#61]
I have followed the instructions how to setup h54s, but cannot get authentication to work.  I tried to use the h54s-angular-seed application, but after entering username / pass (in the popup), I end up in a redirect loop (status code 302).  Creating a small app where I manually call adapter.login(..) I get the same.

Really cant figure out why.  Currently using SAS 9.4 M3.  Opening the stored process (via sas portal) using h54s works fine.  Using Chrome.

Any help would be appreciated.

**Comment by rohnny** [comment]
I am now launching the script from inside the sas portal (which means that I am already authenticatd), and it is then working fine. :)  Not had time to look closer on why it is failing if run from external web application.  I was running the web app from localhost, but were using external adr when testing.

**Comment by boemska-nik** [comment]
Closing
