### ISSUE TITLE
adapter throws error when numeric cell contains missing (.) value

### ISSUE THREAD

**Issue by allanbowe** [Boemska/h54s#67]
A period should be recognised by javascript as a valid numeric character when the spec cell type is numeric.

Also, additional debug information should be thrown.

**Comment by boemska-nik** [comment]
@allanbowe I know this was from a while ago but I'm not sure what this is about. You mention spec cell type - is this a handsontable artifact?

**Comment by boemska-nik** [comment]
Is this related to #59
