### ISSUE TITLE
Possible to specify encoding when serializing json

### ISSUE THREAD

**Issue by rohnny** [Boemska/h54s#69]
Is it possible to specify somehow what encoding to use when serializing json? I mean inside config of h54s.
I have run into issue with using norwegian letters in javascript, and trying to send that over to sas.

**Comment by rohnny** [comment]
I sort of solved this by running urlencode(str) on the client side and then urldecode on the server side, before / after h54s call.  I also added options URLENCODING=UTF8; on the server side.  Seems like this solved the issue with using scandinavian letters for me.

**Comment by boemska-nik** [comment]
Closing, `URLENCODING=UTF8` seems to be the answer until the dev branch is mainline
