### ISSUE TITLE
Update documentation to include example of h54sConfig.json format

### ISSUE THREAD

**Issue by boemska-nik** [Boemska/h54s#73]
This is just a json object that contains overrides to the constructor, but the documentation around how it works right now is ambiguous.

**Comment by cj13579** [comment]
@boemska-nik we now have a [wiki page](https://github.com/Boemska/h54s/wiki/JavaScript-API-Reference) dedicated to the h54s JavaScript API which, pretty close to the top, contains an example of the JSON object that you are referring to. Is there some other stuff that you want to add in this regard or was this what you were thinking of?

**Comment by boemska-nik** [comment]
I'll add a paragraph around how this works into that wiki. Let's leave this open for now.

(but yeah, it's literally just that object in a h54sConfig.json file in the root of the application, as an override to the params in the code)

**Comment by boemska-nik** [comment]
Wiki now [updated](https://github.com/Boemska/h54s/wiki/JavaScript-API-Reference/ebe2493c0d64aee7c9cf7133bfb72ee37d44f156), closing this.
