### ISSUE TITLE
Support for newline character

### ISSUE THREAD

**Issue by allanbowe** [Boemska/h54s#74]
The current development branch uses newline (`\n`) as an input record delimiter, making embedded newlines  (like those found in Excel when pressing "shift + enter") tricky to handle.

It is proposed to use CRLF (`\r\n`) as a record delimiter instead, thereby enabling embedded newlines in the CSV.

**Comment by cj13579** [comment]
This is a really good change. Included as part of the latest releases (v1.0 and 2.0).

Closing.
