### ISSUE TITLE
Authentication status

### ISSUE THREAD

**Issue by Ices-Eyes** [Boemska/h54s#76]
Hi. I just started developing with this very good library, but stucked on a problem. I'm developing a page on a stored process server that is configured for guest access too. The page need to show basic information for not authenticated users, while it has to show more controls if the user is logged in. So, is there a way to check if a user is already authenticated before calling the h54s lib? I need to set the correct SASStoredProcess/do or SASStoredProcess/guest url before using it.

Also, is there a way to make a sync call to a STP insted of an async one?

Thanks :)

**Comment by boemska-nik** [comment]
You should be able to tell whether the user is logged in by looking at the `requestingUser` variable that's returned as part of every call, and use that to retrieve basic data (from STPs that guest users have access to in Metadata). Every call returns the ID of the user (see [here](https://github.com/Boemska/h54s/blob/master/sasautos/h54s.sas#L426)). You can use this to decide how much you render at the front-end, or decide to show a modal that will allow for optional full authentication that submits credentials to `adapter.login()`. 

The library autodetects redirects to SASLogon and caters for the timeouts. Have a look at the example implementation in AngularJS [here](https://github.com/Boemska/sas-hot-editor/blob/master/app/components/sasAdapter.js#L45) (yes it's old but it's clean :)

**Comment by boemska-nik** [comment]
Ah ok @Ices-Eyes , I understand this now I think. You can configure a main adapter instance and use it to try to access any program that requires a login with the default /do configuration. If your user is not logged in the call request will return a [notloggedin](https://github.com/boemska/h54s#callsasprogram-tablesobj-callback) error. When you handle that error in your code, you can create a second instance of the adapter (something like `var anonAdapter = new h54s({"url":"/SASStoredProcess/anon"})` and proceed to use that for your subsequent requests.

Does that make sense?

**Comment by Ices-Eyes** [comment]
Hi,
yes, it makes sense, I used a similar approach in order to circumvent the problem, that is as the following:
``
    if(err) {
            if(err.type === 'notLoggedinError' || err.type === 'loginError') {
                sasAdapter.url='/SASStoredProcess/guest';
                sasAdapter._disableCalls=false;
            }
        }
        else if(res && res.requestingPerson === 'webanon') {
            sasAdapter.url='/SASStoredProcess/guest';
            sasAdapter._disableCalls=false;
        }
``

**Comment by boemska-nik** [comment]
Great! Closing this
