### ISSUE TITLE
h54s Decoding Issue for French Characters

### ISSUE THREAD

**Issue by joeyUOFA** [Boemska/h54s#77]
We met some issues to decode the French characters using h54s. Our SAS system uses windows - 1252 to encode the data. Character É will be encoded as C9. Then when h54s decodes the data sent from SAS, it throws error - The URI to be decoded is not a valid encoding.

**Comment by allanbowe** [comment]
Hi joey,

Can you try adding the following to your SAS stored process?  

`options URLENCODING=UTF8;`

Let us know if it works for you

/Allan

**Comment by joeyUOFA** [comment]
It works. Thanks.

**Comment by allanbowe** [comment]
Also addressed here:  https://github.com/Boemska/h54s/issues/36

**Comment by allanbowe** [comment]
@joeyUOFA  - you may consider (if you haven't already) adding this to your STP autoexec, or sticking it in the `h54s.sas` file itself, whichever works best for your situation.
