### ISSUE TITLE
support for SAS side error handling

### ISSUE THREAD

**Issue by allanbowe** [Boemska/h54s#79]
On the SAS side it is possible to detect / handle an error condition, and reset the return code (eg with `stpsrvset('program error', 0)` and `%let syscc=0;`) such that a 200 response will be returned.

However, it is not possible to remove lines that begin with the word `ERROR` in the log - which causes the adapter to throw a `h54sError`.  This isn't a problem when `debug` mode is off, but does prevent bespoke error handling when it is turned on.

A proposed solution is to prevent `h54sError` from being thrown if the following are true:

* response is 200
* json is valid
* json contains an object named `h54sAbort`

A macro to handle this case can be found [here](https://github.com/Boemska/macrocore/blob/master/base/mf_abort.sas#L68).

**Comment by boemska-nik** [comment]
Up for this, makes sense. That error handling mechanism is out of date

**Comment by boemska-nik** [comment]
Coming back to this now - is the idea that your proposed `h54sAbort` object replaces the existing `status` object and the associated [&h54src and &logmessage macro mechanisms](https://github.com/Boemska/h54s/blob/d1579b31b9efec20dd7327b11b0331e64bfdb953/sasautos/h54s.sas#L140) that are managed by the footer?

**Comment by boemska-nik** [comment]
Also, in terms of how this relates to #41 is this just a question of the text `ERROR:` appearing in the log during a debug run?
