### ISSUE TITLE
maxXhrRetries should be lowered

### ISSUE THREAD

**Issue by allanbowe** [Boemska/h54s#80]
Some customers (even on M6) are getting an "Unable to load Workspaces" error due to the maxing out of multibridge connections / queue slots when errors are thrown.  Workarounds:

* increase multibridge connections from 3
* manually apply `maxXhrRetries` to a lower number

The default of 5 retries is pretty high, as this can mean 18 requests if an app has, say, three calls that all error.

Perhaps a better default should be 2 (meaning, 3 requests per service if they all error).  Or even, zero.

**Comment by boemska-nik** [comment]
The answer to this is to avoid designs that require calling multiple services in parallel (as a best practice), and to implement graceful error handling within the SAS code (which you've done in #81). 

If neither is possible and this is still required, maxXhrRetries can be overridden when instantiating a new adapter in the config json - something along the lines of this:

`var adapter = new h54s({
  maxXhrRetries: 1
});`

Closing
