### ISSUE TITLE
adapter changing two double quotes to one in response

### ISSUE THREAD

**Issue by allanbowe** [Boemska/h54s#82]
The following section in `methods/utils.js` converts two double quotes to one:

```
var responseReplace = function(res) {
  return res.replace(/(\r\n|\r|\n)/g, '').replace(/\\\\(n|r|t|f|b)/g, '\\$1').replace(/\\"\\"/g, '\\"');
};
```
The commit message implies that this is due to the json->CSV work however this is being applied to the _response_ (ie, is unrelated to the CSV export / upload).

Desired behaviour - data from SAS is available in the `res` object without modification.

**Comment by boemska-nik** [comment]
Looking back at the conversations this was an assumption by @bojan88 that because we were converting " -> "" on our way in to SAS to mask quotes in the CSV object we needed to unmask them on the way out. Good catch
