### ISSUE TITLE
Just a little improvement to suggest

### ISSUE THREAD

**Issue by Ices-Eyes** [Boemska/h54s#84]
Hi all,
during some implementation with this fantastic library, I made two little improvements to the proc json used to outpuit data. One is to limit the amount of data transfered, by making option the pretty print of the output, and the other is to allow to output a table as an array instead of a collection of objects. I found sometimes more usefoul this way, ie when using DataTables library.
Following the code I used, that maybe could be improved to be used ie also on version < 9.4...
Hope this could be of any help :)

```
%macro bafOutDataset(outputas, outlib, outdsn, pretty=false, arrayout=false);

  %if %sysevalf(&sysver ge 9.4) %then %do;
    data _null_;
      file _webout;
      put '"' "&outputas." '" : ';
    run;
    options validvarname=upcase;
    proc json out=_webout
        %if %lowcase(&pretty.) ne false %then %do; pretty %end;
        %else %do;
            %if %symExist(_debug) %then %do;
                %if &_debug = 131 %then %do; pretty %end;
            %end;
        %end;
        %if %lowcase(&arrayout.) ne false %then %do; nokeys %end;
      ;
      export &outlib..&outdsn. / nosastags;
    run;

    data _null_;
      file _webout;
      put ',';
    run;
  %end;
  %else %do;
    %bafOutDataset93(&outputas, &outlib, &outdsn)
  %end;
%mend;
```

**Comment by boemska-nik** [comment]
Hey @Ices-Eyes this is a really good idea. It may be a bit slower reconstructing the full table object from the array on the front-end, but it could improve performance considerably!

An updated release of the library is coming up shortly. We'll seriously consider making this part of that release
