### ISSUE TITLE
Update our outdated licence

### ISSUE THREAD

**Issue by boemska-nik** [Boemska/h54s#95]
A couple of people have pointed out that the licence we use is a bit outdated, especially now that RMS has disgraced himself. Let's re-licence under the Apache licence to this and work under those terms moving forward. I don't think we can 'remove' GPL but we can just dual-licence under both moving forward.

Thoughts? @cj13579 @bojan88 @bozazec @boemska-aleksandar

**Comment by bozazec** [comment]
Sounds like great solution 👍

**Comment by boemska-aleksandar** [comment]
Yeah makes sense

**Comment by boemska-nik** [comment]
Sorted. Closing
